name: wallet_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  bip39: ^1.0.6
  bip32: ^2.0.0
  http: ^0.13.4
  intl: ^0.19.0
  dio: ^4.0.0
  web3dart: ^2.3.3
  qr_flutter: ^4.0.0
  ton_dart: ^1.6.0
  share: ^2.0.4
  local_auth: ^2.3.0
  wallet_connect: ^1.0.4
  flutter_cache_manager: ^3.3.0
  url_launcher: 6.3.1
  jovial_svg: 1.1.6
  otp: 3.1.2
  connectivity_plus: ^6.1.4
  elliptic: ^0.3.8
  blockchain_utils: ^5.0.0
  percent_indicator: ^3.4.0
  flutter_svg: ^1.1.6
  page_transition: ^2.0.5
  leb128: ^1.0.1
  hex: ^0.2.0
  ed25519_hd_key: ^2.2.0
  rename: 2.0.1
  flutter_local_notifications: 18.0.1
  font_awesome_flutter: 10.4.0
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.4+5
  awesome_dialog: ^3.2.1
  validators: ^3.0.0
  device_info_plus: ^11.3.0
  eth_sig_util: ^0.0.7
  path: ^1.8.0
  prompt_dialog: ^1.0.9
  flutter_inappwebview: 6.1.5
  scan: ^1.6.0
  cached_network_image: 3.3.0
  decimal: ^2.2.0
  flutter_pin_code_fields: ^1.1.0
  pinput: ^2.2.31
  html: ^0.15.0
  flutter_windowmanager: 0.2.0
  mime: ^1.0.2
  flutter_countdown_timer: ^4.1.0
  worker_manager: ^4.4.6
  shimmer: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  package_info_plus: ^8.3.0
  bs58check: ^1.0.2
  bech32: 0.2.2
  sha3: ^0.2.0
  stellar_flutter_sdk: ^1.3.7
  path_provider: ^2.0.11
  oxidized: ^5.2.0
  flutter_downloader: ^1.9.1
  permission_handler: ^10.2.0
  vibration: ^3.1.3
  wallet: ^0.0.18
  flutter_secure_storage: ^6.1.0
  hive_test: ^1.0.1
  hash: ^1.0.4
  base_x: ^2.0.0
  cbor: ^4.1.0
  upgrader: ^11.4.0
  encrypt: ^5.0.1
  flutter_riverpod: ^2.3.7
  event_bus: ^2.0.0
  on_chain: ^6.6.0
  borsh_annotation: ^0.3.1+5
  laksadart: ^0.2.1+1
  wallet_connect_dart_v2: ^0.0.1
  fuse_wallet_sdk: ^0.3.5
  starknet: ^0.1.2+1
  flutter_dotenv: ^5.0.2
  langchain: ^0.7.7+2
  dash_chat_2: ^0.0.21
  logger: ^1.1.0
  langchain_openai: ^0.7.3
  solana: ^0.31.2+1
  screenshot_callback: ^3.0.1
  animated_splash_screen: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  xxh64: ^0.0.3+1
  polkadart_scale_codec: ^1.3.0
  substrate_metadata: ^1.3.0
  cryptography: 2.7.0
  starknet_provider: ^0.1.1+1
  fraction: 5.0.3
  http_parser: 4.0.2
  web_socket_channel: 2.4.0
  freezed_annotation: 2.4.4
  ed25519_edwards: 0.3.1
  string_similarity: ^2.0.0
  jazzicon:
    path: ./jazzicon
  near_api_flutter:
    path: ./near_api_flutter
  bitcoin_flutter:
    path: ./bitcoin_flutter
  bitbox:
    path: ./bitbox
  solana_name_service:
    path: ./solana_name_service
  sui:
    path: ./sui
  charts_flutter:
    path: ./charts_flutter-0.12.0
  alan:
    path: ./alan
  tonutils:
    path: ./tonutils-dart
  multiversx_sdk:
    path: ./multiversx_sdk

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
dependency_overrides:
  http: ^0.13.4
  cached_network_image: ^3.3.1
  web_socket_channel: ^3.0.0
  uuid: ^4.0.0
  freezed_annotation: 2.4.4
  intl: ^0.19.0
  dio: ^5.5.0+1
  decimal: ^2.2.0
  ffi: 2.0.0
  pinenacl: ^0.6.0
  pointycastle: ^3.4.0
  starknet:
    git:
      url: https://github.com/focustree/starknet.dart
      path: packages/starknet
  starknet_provider:
    git:
      url: https://github.com/focustree/starknet.dart
      path: packages/starknet_provider
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/currency_flags/
    - assets/images/
    - json/
    - js/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
