/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:event_bus/event_bus.dart';
import 'package:wallet_app/interface/coin.dart';

abstract class EventBusService {
  static final instance = EventBus();
}

class CryptoNotificationEvent {
  final String title;
  final String body;

  CryptoNotificationEvent({
    required this.title,
    required this.body,
  });
}

class SeedPharseInitializationEvent {
  final Coin coin;

  SeedPharseInitializationEvent({
    required this.coin,
  });
}
